name: Build & Security Check

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js (if applicable)
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        if: hashFiles('package.json') != ''
        run: npm ci || npm install

      - name: Check for vulnerabilities
        if: hashFiles('package.json') != ''
        run: npm audit --audit-level=high || true

      - name: Build
        if: hashFiles('package.json') != ''
        run: |
          if grep -q '"build"' package.json; then
            npm run build
          fi

      - name: Run tests
        if: hashFiles('package.json') != ''
        run: |
          if grep -q '"test"' package.json; then
            npm test
          fi

      - name: Mark as stable
        run: |
          echo "✅ BUILD STATUS: STABLE"
          echo "All checks passed successfully"
